# Generated by Django 6.0 on 2026-01-23 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0004_budgetlimit"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="goal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contributions",
                to="transactions.goal",
            ),
        ),
    ]
